*** IMPORT NEW CROSS SELL FILES. INSTRUCTIONS HERE:                ***;
*** `R:\Production\MLA\Files for MLA PROCessINg\XSELL\             ***;
*** XSELL TCI DECSION LENDER.tXt`. CHANGE DATES IN THE LINES       ***;
*** IMMEDIATELY BELOW ALONG WITH FILE PATHS. FOR THE FILES PATHS,  ***;
*** YOU WILL LIKELY NEED TO CREATE A NEW FOLDER "ITA" IN THE       ***;
*** APPROPRIATE MONTH FILE. DO NOT CHANGE THE ARGUMENT TO THE LEFT ***;
*** OF THE COMMA - ONLY CHANGE WHAT IS TO THE RIGHT OF THE COMMA.  ***;

*** STEP 1: PULL ALL DATA AND SEND TO DOD ------------------------ ***;
DATA _NULL_;
CALL SYMPUT('_7YR','2011-05-12');
CALL SYMPUT('_6YR','2012-05-11');
CALL SYMPUT ('_1YR','2017-05-10');
CALL SYMPUT ('_1DAY','2018-05-09');
CALL SYMPUT ('Retail_ID', 'RetailXSITA6.0_2018');
CALL SYMPUT ('AUTO_ID', 'AUTOXSITA6.0_2018');
CALL SYMPUT ('FB_ID', 'FBITA6.0_2018');
CALL SYMPUT ('FINALEXPORTFLAGGED', 
	'\\mktg-APP01\E\Production\2018\06-JuNE_2018\ITA\FBXS_ITA_20180510FLAGGEd.tXt');
CALL SYMPUT ('FINALEXPORTDROPPED', 
	'\\mktg-APP01\E\Production\2018\06-JuNE_2018\ITA\FBXS_ITA_20180510FINal.tXt');
CALL SYMPUT ('EXPORTMLA1', 
	'\\mktg-APP01\E\Production\MLA\MLA-INPUT files TO WEBSITE\FB_MITA_20180510p1.tXt');
CALL SYMPUT ('EXPORTMLA2', 
	'\\mktg-APP01\E\Production\MLA\MLA-INPUT files TO WEBSITE\FB_MITA_20180510p2.tXt');
CALL SYMPUT ('FINALEXPORTED', 
	'\\mktg-APP01\E\Production\2018\06-JuNE_2018\ITA\FBXSPB_ITA_20180510fINal_HH.csv');
CALL SYMPUT ('FINALEXPORTHH', 
	'\\mktg-APP01\E\Production\2018\06-JuNE_2018\ITA\FBXSPB_ITA_20180510fINal_HH.tXt');
CALL SYMPUT ('FINALEXPORTED2', 
	'\\mktg-APP01\E\Production\2018\06-JuNE_2018\ITA\FBXS_ITA_20180510fINal_HH.csv');
CALL SYMPUT ('FINALEXPORTHH2', 
	'\\mktg-APP01\E\Production\2018\06-JuNE_2018\ITA\FBXS_ITA_20180510fINal_HH.tXt');
RUN;

%PUT "&_1YR" "&_1DAY";

*** OLD TCI 3.5 DATA - Retail AND AUTO --------------------------- ***;
PROC IMPORT 
	DATAFILE = "\\mktg-APP01\E\Production\MLA\Files for MLA PROCessINg\XSELL\TCI3_5.tXt" 
		OUT =  TCI2 REPLACE DBMS = DLM;
	DELIMITER = '09'X;
	GUESSINGROWS = MAX;
RUN;

DATA TCI3;
	SET TCI2;
	SSN = PUT(INPUT(SSNO1 ,BEst32.), z9.);
	SS7 = PUT(INPUT(SSNO1_RT7, BEst32.), z7.);
	APPNUM = STRIP(PUT('APPLICATION NUMBER'n, 10.));
	DROP SSNO1 SSNO1_RT7 'APPLICATION NUMBER'n;
	RENAME SSN = SSNO1 SS7 = SSNO1_RT7 APPNUM = 'APPLICATION NUMBER'n;
RUN;

*** NEW TCI DATA - Retail AND AUTO ------------------------------- ***;
PROC IMPORT 
	DATAFILE = "\\mktg-APP01\E\cepps\FBXMITA\XS_Mail_PULL.XlsX" 
		DBMS = XLSX OUT = NEWXS REPLACE;
	RANGE = "XS Mail PULL$A3:0";
	GETNAMES = YES;
RUN;

DATA NEWXS2;
	SET NEWXS;
	IF 'LOAN TYPE'n = "Auto Indirect" THEN SOURCE = "TCICentral";
	IF 'LOAN TYPE'n = "Retail" THEN SOURCE = "TCIRetail";
	IF SOURCE NE "";

	IF FIND('APPLICANT ADDRESS'n, "APT") = 0  THEN DO;
		ADR1 = SCAN('APPLICANT ADDRESS'n, 1, ",");
		CITY = SCAN('APPLICANT ADDRESS'n, 2, ",");
		STATE = SCAN('APPLICANT ADDRESS'n, 3, ",");
		ZIP = SCAN('APPLICANT ADDRESS'n, 4, ",");
	END;

	IF FIND('APPLICANT ADDRESS'n,"APT") GE 1 THEN DO;
		ADR1 = SCAN('APPLICANT ADDRESS'n, 1, ",");
		ADR2 = SCAN('APPLICANT ADDRESS'n, 2, ",");
		CITY = SCAN('APPLICANT ADDRESS'n, 3, ",");
		STATE = SCAN('APPLICANT ADDRESS'n, 4, ",");
		ZIP = SCAN('APPLICANT ADDRESS'n, 5, ",");
	END;

	DOB = PUT('APPLICANT DOB'n, YYmmdd10.);
	'APPLICATION DATE1'n = PUT('APPLICATION DATE'n, mmddYY10.);
	BRACCTNO = CATS("TCI", 'APPLICATION NUMBER'n);
	SSNO1_RT7 = SUBSTRn('APPLICANT SSN'n, MAX(1, LENGTH('APPLICANT SSN'n) - 6), 7);
	DROP 'APPLICATION DATE'n 
		 'APPLICANT ADDRESS'n
		 'APPLICANT ADDRESS ZIP'n 
		 'APPLICANT DOB'n 
		 'APP. WORK PHONE'n;
	RENAME 'APPLICATION DATE1'n = 'APPLICATION DATE'n 
		   'APPLICANT EMAIL'n = EMAIL 
		   'APPLICANT CREDIT SCORE'n = CRSCORE 
		   'APPLICANT FIRST NAME'n = FIRSTNAME 
		   'APPLICANT LAST NAME'n = LASTNAME 
		   'APPLICANT SSN'n = SSNO1 
		   'APPLICANT MIDDLE NAME'n = MIDDLENAME 
		   'APP. CELL PHONE'n = CELLPHONE 
		   'APP. HOME PHONE'n = PHONE;
RUN;

DATA TCI;
	LENGTH ADR1 $40 
		   CITY $25 
		   STATE $4 
		   ZIP $10 
		   MIDDLENAME $25 
		   SOURCE $11 
		   BRACCTNO $15;;
	SET TCI3 NEWXS2;
	SSNO1 = STRIP(SSNO1);
	DOB = COMPRESS(DOB, "-");
	FORMAT _CHARACTER_;
RUN;

*** PULL IN XS FROM LOAN TABLE, BORROWER TABLE AND MERGE --------- ***;
DATA XS_L;
	SET DW.vw_Loan_NLS(
		KEEP = OWNST XNO_AVAILCREDIT XNO_TDUEPOFF CIFNO BRACCTNO ID
			   SSNO1 OWNBR SSNO1_RT7 SSNO2 LNAMT FINCHG LOANTYPE
			   ENTDATE LOANDATE CLASSID CLASSTRANSLATION
			   XNO_TRUEDUEDATE FIRSTPYDATE SRCD POCD POFFDATE PLCD
			   PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER CONPROFILE1
			   DATEPAIDLAST APRATE CRSCORE CURBAL);
	WHERE CIFNO NE "" & ENTDATE >= "&_1YR" & POCD = "" & PLCD = "" & 
		  PLDATE = "" & POFFDATE = ""  & BNKRPTDATE = "" &
		  CLASSID IN (10, 19, 20, 31, 34) &
		  OWNST IN ("SC","NM","NC","OK","VA","TX","AL","GA","TN");
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	IF CIFNO NOT =: "B";
RUN;

PROC SQL;
	CREATE TABLE XS_LDEDUPED AS
	SELECT *
	FROM XS_L
	GROUP BY CIFNO
	HAVING ENTDATE = MAX(ENTDATE);
QUIT;

DATA BORRNLS;
	LENGTH FIRSTNAME $20 MIDDLENAME $20 LASTNAME $30;
	SET DW.vw_Borrower(
		KEEP = RMC_UPDATED PHONE CELLPHONE CIFNO SSNO SSNO_RT7 FNAME
			   LNAME ADR1 ADR2 CITY STATE ZIP BRNO AGE CONFIDENTIAL
			   SOLICIT CEASEANDDESIST CREDITSCORE);
	WHERE CIFNO NOT =: "B";
	FNAME = STRIP(FNAME);
	LNAME = STRIP(LNAME);
	ADR1 = STRIP(ADR1);
	ADR2 = STRIP(ADR2);
	CITY = STRIP(CITY);
	STATE = STRIP(STATE);
	ZIP = STRIP(ZIP);

	IF FIND(FNAME, "JR") GE 1 THEN DO;
		FIRSTNAME = COMPRESS(FNAME, "JR");
		SUFFIX = "JR";
	END;

	IF FIND(FNAME, "SR") GE 1 THEN DO;
		FIRSTNAME = COMPRESS(FNAME, "SR");
		SUFFIX = "SR";
	END;

	IF SUFFIX = "" THEN DO;
		FIRSTNAME = SCAN(FNAME, 1, 1);
		MIDDLENAME = CATX(" ", SCAN(FNAME, 2, " "), 
							   SCAN(FNAME, 3, " "), 
							   SCAN(FNAME, 4, " "));
	END;

	NWORDS = COUNTW(FNAME, " ");

	IF NWORDS > 2 & SUFFIX NE "" THEN DO;
		FIRSTNAME = SCAN(FNAME, 1, " ");
		MIDDLENAME = SCAN(FNAME, 2, " ");
	END;

	DOB = COMPRESS(AGE, "-");
	LASTNAME = LNAME;
	DROP FNAME LNAME NWORDS AGE;
	IF CIFNO NE "";
RUN;

PROC SORT 
	DATA = XS_LDEDUPED NODUPKEY; 
	BY CIFNO; 
RUN;

PROC SORT 
	DATA = BORRNLS; 
	BY CIFNO DESCENDING RMC_UPDATED; 
RUN;

PROC SORT 
	DATA = BORRNLS OUT = BORRNLS2 NODUPKEY; 
	BY CIFNO; 
RUN;

DATA LOANNLSXS;
	MERGE XS_LDEDUPED(IN = X) BORRNLS2(IN = Y);
	BY CIFNO;
	IF X AND Y;
RUN;

*** MODIFY AS NEEDED WHEN MORE STATES CONVERT TO NLS ------------- ***;
DATA LOANEXTRAXS;
	SET DW.vw_Loan(
		KEEP = XNO_AVAILCREDIT XNO_TDUEPOFF BRACCTNO ID SSNO1 OWNBR
			   OWNST SSNO1_RT7 SSNO2 LNAMT FINCHG LOANTYPE ENTDATE
			   LOANDATE CLASSID CLASSTRANSLATION XNO_TRUEDUEDATE
			   FIRSTPYDATE SRCD POCD POFFDATE PLCD PLDATE PLAMT
			   BNKRPTDATE BNKRPTCHAPTER CONPROFILE1 DATEPAIDLAST APRATE
			   CRSCORE CURBAL);
	WHERE ENTDATE >= "&_1YR" & POCD = "" & PLCD = "" & PLDATE = "" &
		  POFFDATE = ""  & BNKRPTDATE = "" &
		  CLASSID IN (10, 19, 20, 31, 34) &
		  OWNST IN ("SC","NM","NC","OK","VA","TX","AL","GA","TN");
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
IF SSNO1=: "99" THEN BADSSN="X";  *FLAG BAD SSNS;
IF SSNO1=: "98" THEN BADSSN="X";
RUN;

*** IDENTIFY LOANS IN NLS STATES THAT ARE NOT IN vw_Loan_NLS ----- ***;
DATA LOAN1_2XS;
	SET XS_L;
	KEEP BRACCTNO;
RUN;

PROC SORT 
	DATA = LOAN1_2XS; 
	BY BRACCTNO; 
RUN;

PROC SORT 
	DATA = LOANEXTRAXS; 
	BY BRACCTNO; 
RUN;

DATA LOANEXTRA2XS;
	MERGE LOANEXTRAXS(IN = X) LOAN1_2XS(IN = Y);
	BY BRACCTNO;
	IF X AND NOT Y;
RUN;

*** MODIFY AS STATES CONVERT. WHEN ALL STATES ARE CONVERTED, THIS  ***;
*** SECTION CAN BE REMOVED --------------------------------------- ***;
DATA LOANPARADATAXS;
	SET DW.vw_Loan(
		KEEP = BRACCTNO XNO_AVAILCREDIT XNO_TDUEPOFF ID OWNBR OWNST
			   SSNO1 SSNO2 SSNO1_RT7 LNAMT FINCHG LOANTYPE ENTDATE 
			   LOANDATE CLASSID CLASSTRANSLATION XNO_TRUEDUEDATE
			   FIRSTPYDATE SRCD POCD POFFDATE PLCD PLDATE PLAMT
			   BNKRPTDATE BNKRPTCHAPTER DATEPAIDLAST APRATE CRSCORE
			   NETLOANAMOUNT XNO_AVAILCREDIT XNO_TDUEPOFF CURBAL
			   CONPROFILE1);
	WHERE ENTDATE >= "&_1YR" & PLCD = "" & POCD = "" & POFFDATE = "" &
		  PLDATE = "" & BNKRPTDATE = "" & 
		  OWNST NOT IN ("SC","NM","NC","OK","VA","TX","AL","GA","TN") &
		  CLASSID IN (10, 19, 20, 31, 34);
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	IF SSNO1 =: "99" THEN BADSSN = "X"; /* FLAG BAD SSNS */
	IF SSNO1 =: "98" THEN BADSSN = "X"; 
RUN;

DATA SET1XS;
	SET LOANPARADATAXS LOANEXTRA2XS;
RUN;

DATA BORRPARADATA;
	LENGTH FIRSTNAME $20 MIDDLENAME $20 LASTNAME $30;
	SET DW.vw_Borrower(
		KEEP = RMC_UPDATED PHONE CELLPHONE CIFNO SSNO SSNO_RT7 FNAME
			   LNAME ADR1 ADR2 CITY STATE ZIP BRNO AGE CONFIDENTIAL
			   SOLICIT CEASEANDDESIST CREDITSCORE);
	FNAME = STRIP(FNAME);
	LNAME = STRIP(LNAME);
	ADR1 = STRIP(ADR1);
	ADR2 = STRIP(ADR2);
	CITY = STRIP(CITY);
	STATE = STRIP(STATE);
	ZIP = STRIP(ZIP);

	IF FIND(FNAME, "JR") GE 1 THEN DO;
		FIRSTNAME = COMPRESS(FNAME, "JR");
		SUFFIX = "JR";
	END;

	IF FIND(FNAME, "SR") GE 1 THEN DO;
		FIRSTNAME = COMPRESS(FNAME, "SR");
		SUFFIX = "SR";
	END;

	IF SUFFIX = "" THEN DO;
		FIRSTNAME = SCAN(FNAME, 1, 1);
		MIDDLENAME = CATX(" ", SCAN(FNAME, 2, " "), 
							   SCAN(FNAME, 3, " "), 
							   SCAN(FNAME, 4, " "));
	END;
	NWORDS = COUNTW(FNAME, " ");

	IF NWORDS > 2 & SUFFIX NE "" THEN DO;
		FIRSTNAME = SCAN(FNAME, 1, " ");
		MIDDLENAME = SCAN(FNAME, 2, " ");
	END;

	DOB = COMPRESS(AGE,	"-");
	SS7BRSTATE = CATS(SSNO_RT7, SUBSTR(BRNO, 1, 2));
	LASTNAME = LNAME;
	RENAME SSNO_RT7 = SSNO1_RT7 SSNO = SSNO1;
	IF SSNO =: "99" THEN BADSSN = "X"; /* FLAG BAD SSNS */
	IF SSNO =: "98" THEN BADSSN = "X"; 
	DROP NWORDS FNAME LNAME AGE;
RUN;

DATA goodSSN_lXs BADSSN_lXs;
SET SET1XS;
IF BADSSN="X" THEN OUTPUT BADSSN_lXs;
else OUTPUT goodSSN_lXs;
RUN;
DATA goodSSN_b BADSSN_b;
SET BORRPARADATA;
IF BADSSN="X" THEN OUTPUT BADSSN_b;
else OUTPUT goodSSN_b;
RUN;


PROC SORT DATA=goodSSN_lXs; BY SSNO1; RUN;
PROC SQL;
CREATE TABLE goodSSN_lXs AS
SELECT *
FROM goodSSN_lXs
GROUP BY SSNO1
HAVING ENTDATE = MAX(ENTDATE);
QUIT;
PROC SORT DATA=goodSSN_lXs NODUPKEY; BY SSNO1; RUN;
PROC SORT DATA=goodSSN_b; BY SSNO1 DESCENDING RMC_UPDATED; RUN;
PROC SORT DATA=goodSSN_b NODUPKEY; BY SSNO1; RUN;
DATA MERGEdgoodSSNXs;
MERGE goodSSN_lXs(IN=X) goodSSN_b(IN=Y);
BY SSNO1;
IF X AND Y;
RUN;

PROC SORT DATA=BADSSN_lXs; BY SS7BRSTATE; RUN;
PROC SQL;
CREATE TABLE BADSSN_lXs AS
SELECT *
FROM BADSSN_lXs
GROUP BY SS7BRSTATE
HAVING ENTDATE = MAX(ENTDATE);
QUIT;
PROC SORT DATA=BADSSN_lXs NODUPKEY; BY SS7BRSTATE; RUN;
PROC SORT DATA=BADSSN_b; BY SS7BRSTATE DESCENDING RMC_UPDATED; RUN;
PROC SORT DATA=BADSSN_b NODUPKEY; BY SS7BRSTATE; RUN;
DATA MERGEdBADXs;
MERGE BADSSN_lXs(IN=X) BADSSN_b(IN=Y);
BY SS7BRSTATE;
IF X AND Y;
RUN;

PROC SORT DATA=MERGEdBADXs OUT=MERGEdBADSSNXs NODUPKEY; BY SS7BRSTATE; RUN;

DATA SSNS;
SET MERGEdgoodSSNXs MERGEdBADSSNXs;
RUN;

PROC SORT DATA=SSNS NODUPKEY; BY BRACCTNO; RUN;
PROC SORT DATA=LOANNLSXS NODUPKEY; BY BRACCTNO; RUN;

DATA paraDATA;
MERGE LOANNLSXS(IN=X) SSNS(IN=Y);
BY BRACCTNO;
IF NOT X AND Y;
RUN;

DATA Xs;
SET LOANNLSXS paraDATA;
RUN; 



*MERGE XS FROM our DW with INfo FROM TCI sites TO IDENTIFY mades AND PULL IN unmades;
PROC SORT DATA=XS; BY SSNO1; RUN;
PROC SORT DATA=tci; BY SSNO1; RUN;
DATA tcimades;
SET tci;
DROP BRACCTNO;
RUN;
DATA mades;
MERGE XS(IN=X) tcimades(IN=Y);
BY SSNO1;
IF X=1;
RUN;
DATA unmades;
MERGE XS(IN=X) tci(IN=Y);
BY SSNO1;
IF X=0 AND Y=1;
made_unmade="UNMADE";
RUN;

DATA mades2;  *for matched, KEEP onlY INfo FROM LOAN AND BORROWER TABLEs;
SET mades (KEEP=BRACCTNO SSNO1 ID OWNBR SSNO1_RT7 SSNO2 LNAMT FINCHG LOANTYPE ENTDATE LOANDATE CLASSID CLASSTRANSLATION SRCD POCD POFFDATE PLCD PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER CONPROFILE1 DATEPAIDLAST APRATE CRSCORE CURBAL ADR1 ADR2 CITY STATE ZIP DOB CONFIDENTIAL SOLICIT CEASEANDDESIST CREDITSCORE FIRSTNAME MIDDLENAME LASTNAME SS7BRSTATE PHONE CELLPHONE);
made_unmade="MADE";
RUN;
DATA XSTOt; *APPEND mades AND unmades for full XS universe;
SET unmades mades2;
DROP NWORDS;
RUN;

DATA XsTOt;
SET XsTOt;
IF SS7BRSTATE="" THEN SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
IF CRSCORE <625 THEN Risk_Segment="624 AND BElow";
IF 625<=CRSCORE<650 THEN Risk_Segment="625-649";
IF 650<=CRSCORE<851 THEN Risk_Segment="650-850";
IF CLASSID IN (10,21,31) THEN SOURCE_2="Retail";
IF SOURCE="TCIRetail" THEN SOURCE_2="Retail";
IF CLASSID IN (13,14,19,20,32,34,40,41,45,68,69,72,75,78,79,80,88,89,90) THEN SOURCE_2="Auto";
IF SOURCE = "TCICentral" THEN SOURCE_2="Auto";
RUN;
DATA Xs_TOtal;
LENGTH offer_segment $20;
SET XsTOt;
	IF CRSCORE = 0 THEN BADFico_FLAG="X";
	IF CRSCORE = . THEN BADFico_FLAG="X";
	IF CRSCORE > 850 THEN BADFico_FLAG="X";
	IF STATE="NC" & SOURCE_2="Auto" & made_unmade="UNMADE" THEN NCAUTOUn_FLAG="X";
	IF STATE="NC" & SOURCE_2="Auto" & made_unmade="MADE" THEN offer_segment="ITA";
	IF STATE IN ("GA", "VA") THEN offer_segment="ITA";
	IF STATE IN ("SC","TX","TN","AL","OK","NM") & SOURCE_2="Auto" THEN offer_segment="ITA";
	IF STATE IN ("SC","NC","TX","TN","AL","OK","NM") & SOURCE_2="Retail" & Risk_Segment="624 AND BElow" THEN offer_segment="ITA";
RUN;


*Dedupe XS;
DATA Xs_TOtal;
SET Xs_TOtal;
IF offer_segment = "ITA";  *KEEP onlY ITAS;
camp_tYpe="XS";
RUN;


*PULL IN DATA for FBs;
DATA LOAN_PULL;
SET DW.vw_Loan_NLS (KEEP= CIFNO BRACCTNO ID OWNBR OWNST SSNO1_RT7 SSNO1 SSNO2 LNAMT FINCHG SSNO1_RT7 LOANTYPE ENTDATE LOANDATE CLASSID CLASSTRANSLATION XNO_TRUEDUEDATE FIRSTPYDATE SRCD POCD POFFDATE PLCD PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER DATEPAIDLAST APRATE CRSCORE CURBAL);
WHERE POFFDATE BEtween "&_6YR" AND "&_1DAY" & (POCD="13" or POCD= "10" or POCD= "50") & OWNST IN ("NC","VA","NM","SC","OK","TX");
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
IF CIFNO NOT =: "B";
RUN;


PROC SQL;
CREATE TABLE LOAN1nlsfb AS
SELECT *
FROM LOAN_PULL
GROUP BY CIFNO
HAVING ENTDATE = MAX(ENTDATE);
QUIT;
PROC SORT DATA=LOAN1nlsfb NODUPKEY; BY CIFNO; RUN;
DATA LOANnlsfb;
MERGE LOAN1nlsfb(IN=X) BORRNLS2(IN=Y);
BY CIFNO;
IF X AND Y;
RUN;


DATA LOANEXtrafb; *FIND NLS LOANS NOT IN vw_nls_LOAN;
SET DW.vw_Loan(KEEP= BRACCTNO XNO_AVAILCREDIT XNO_TDUEPOFF ID OWNBR OWNST SSNO1 SSNO2 SSNO1_RT7 LNAMT FINCHG LOANTYPE ENTDATE LOANDATE CLASSID CLASSTRANSLATION XNO_TRUEDUEDATE FIRSTPYDATE SRCD POCD POFFDATE PLCD PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER DATEPAIDLAST APRATE CRSCORE NETLOANAMOUNT XNO_AVAILCREDIT XNO_TDUEPOFF CURBAL CONPROFILE1);
WHERE POFFDATE BEtween "&_6YR" AND "&_1DAY" & (POCD="13" or POCD= "10" or POCD= "50") & OWNST IN("NC","VA","NM","SC","OK","TX");
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
IF SSNO1=: "99" THEN BADSSN="X";  *FLAG BAD SSNS;
IF SSNO1=: "98" THEN BADSSN="X";
RUN;
DATA LOAN1_2fb;
SET LOAN_PULL;
KEEP BRACCTNO;
RUN;
PROC SORT DATA=LOAN1_2fb; BY BRACCTNO; RUN;
PROC SORT DATA=LOANEXtrafb; BY BRACCTNO; RUN;
DATA LOANEXtra2fb;
MERGE LOANEXtrafb(IN=X) LOAN1_2fb(IN=Y);
BY BRACCTNO;
IF X AND NOT Y;
RUN;


DATA LOANparaDATAfb;
SET DW.vw_Loan(KEEP= BRACCTNO XNO_AVAILCREDIT XNO_TDUEPOFF ID OWNBR OWNST SSNO1 SSNO2 SSNO1_RT7 LNAMT FINCHG LOANTYPE ENTDATE LOANDATE CLASSID CLASSTRANSLATION XNO_TRUEDUEDATE FIRSTPYDATE SRCD POCD POFFDATE PLCD PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER DATEPAIDLAST APRATE CRSCORE NETLOANAMOUNT XNO_AVAILCREDIT XNO_TDUEPOFF CURBAL CONPROFILE1);
WHERE POFFDATE BEtween "&_6YR" AND "&_1DAY" & (POCD="13" or POCD= "10" or POCD= "50") & OWNST NOT IN ("NC","VA","NM","SC","OK","TX");
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
IF SSNO1=: "99" THEN BADSSN="X";  *FLAG BAD SSNS;
IF SSNO1=: "98" THEN BADSSN="X"; 
RUN;

DATA SET1fb;
SET LOANparaDATAfb LOANEXtra2fb;
RUN;

DATA goodSSN_lfb BADSSN_lfb;
SET SET1fb;
IF BADSSN="X" THEN OUTPUT BADSSN_lfb;
else OUTPUT goodSSN_lfb;
RUN;

PROC SORT DATA=goodSSN_lfb; BY SSNO1; RUN;
PROC SQL;
CREATE TABLE goodSSN_lfb AS
SELECT *
FROM goodSSN_lfb
GROUP BY SSNO1
HAVING ENTDATE = MAX(ENTDATE);
QUIT;
PROC SORT DATA=goodSSN_lfb NODUPKEY; BY SSNO1; RUN;
PROC SORT DATA=goodSSN_b; BY SSNO1; RUN;
DATA MERGEdgoodSSNfb;
MERGE goodSSN_lfb(IN=X) goodSSN_b(IN=Y);
BY SSNO1;
IF X AND Y;
RUN;

PROC SQL;
CREATE TABLE BADSSN_lfb AS
SELECT *
FROM BADSSN_lfb
GROUP BY SS7BRSTATE
HAVING ENTDATE = MAX(ENTDATE);
QUIT;
PROC SORT DATA=BADSSN_lfb NODUPKEY; BY SS7BRSTATE; RUN;
PROC SORT DATA=BADSSN_b; BY SS7BRSTATE; RUN;
DATA MERGEdBADSSNfb;
MERGE BADSSN_lfb(IN=X) BADSSN_b(IN=Y);
BY SS7BRSTATE;
IF X AND Y;
RUN;

PROC SORT DATA=MERGEdBADSSNfb NODUPKEY; BY SS7BRSTATE; RUN;

DATA SSNSfb;
SET MERGEdgoodSSNfb MERGEdBADSSNfb;
RUN;


PROC SORT DATA=SSNSfb NODUPKEY; BY BRACCTNO; RUN;
PROC SORT DATA=LOANnlsfb NODUPKEY; BY BRACCTNO; RUN;

DATA paraDATA;
MERGE LOANnlsfb(IN=X) SSNSfb(IN=Y);
BY BRACCTNO;
IF NOT X AND Y;
RUN;

DATA fb;
SET LOANnlsfb paraDATA;
camp_tYpe="FB";
RUN; 

*APPEND XS TO FB;
DATA MERGEd_l_b_Xs_fb;
SET fb Xs_TOtal;
RUN;
PROC SORT DATA=MERGEd_l_b_Xs_fb OUT=MERGEd_l_b_Xs_fb2 NODUPKEY; BY BRACCTNO; RUN;

DATA Y;
SET DW.eXclude_LOAN (KEEP=BRACCTNO CONPROFILE1);
RENAME CONPROFILE1=OLDCon;
RUN;

PROC SORT DATA=MERGEd_l_b_Xs_fb2;
BY BRACCTNO;
RUN;
PROC SORT DATA=Y;
BY BRACCTNO;
RUN;

DATA MERGEd_l_b_Xs_fb2;
MERGE MERGEd_l_b_Xs_fb2 (IN=X) Y;
BY BRACCTNO;
IF X;
RUN;

DATA MERGEd_l_b_Xs_fb2;
SET MERGEd_l_b_Xs_fb2;
IF cOLDcon NE "" THEN CONPROFILE1 = OLDcon;
RUN;


*PULL IN INFORMATion for statFLAGs;
DATA StatFLAGs;
SET DW.vw_Loan (KEEP= OWNBR SSNO1_RT7 ENTDATE StatFLAGs);
WHERE ENTDATE > "&_7YR" & statFLAGs NE "";
RUN;
 PROC SQL; *IDENTIFYINg BAD statFLAGs;
 CREATE TABLE statFLAGs2 AS
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "A"
 union 
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "B"
 union
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "C"
 union
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "D"
 union
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "I"
 union
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "J"
 union 
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "L"
  union 
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "P"
  union 
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "R"
	union 
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "V"
union 
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "W"
union 
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "X"
union 
 SELECT * FROM statFLAGs WHERE statFLAGs contaINs "S";
 QUIT;
DATA statFLAGs2; *taggINg BAD statFLAGs;
 SET statFLAGs2;
 statfl_FLAG="X";
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
DROP ENTDATE OWNBR SSNO1_RT7;
RENAME statFLAGs=statFLAGs_OLD;
 RUN;
PROC SORT DATA=statFLAGs2 NODUPKEY; BY SS7BRSTATE; RUN;
PROC SORT DATA=MERGEd_l_b_Xs_fb2; BY SS7BRSTATE; RUN;
DATA MERGEd_L_B2; *MERGE file with statFLAG FLAGs;
MERGE MERGEd_l_b_Xs_fb2(IN=X) statFLAGs2;
BY SS7BRSTATE;
IF X=1;
RUN;


DATA MERGEd_l_b2;
SET MERGEd_l_b2;
IF BNKRPTDATE NE "" THEN bk5_FLAG="X";
IF BNKRPTCHAPTER NOT IN (0,.) THEN bk5_FLAG="X";
RUN;


*FLAG BAD TRW status;
DATA trwstatus_fl;
SET DW.vw_Loan (KEEP= OWNBR SSNO1_RT7 ENTDATE trwstatus);
WHERE ENTDATE > "&_7YR" & TrwStatus NE "";
RUN;
DATA trwstatus_fl; *FLAG for BAD trw's;
SET trwstatus_fl;
TRW_FLAG = "X";
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
DROP ENTDATE SSNO1_RT7 OWNBR;
RUN;
PROC SORT DATA=trwstatus_fl NODUPKEY; BY SS7BRSTATE; RUN;
PROC SORT DATA=MERGEd_l_b2; BY SS7BRSTATE; RUN;
DATA MERGEd_L_B2; *MERGE PULL with trw FLAGs;
MERGE MERGEd_L_B2(IN=X) trwstatus_fl;
BY SS7BRSTATE;
IF X;
RUN;


*IDENTIFY BAD PO Codes;
DATA PO_codes_5Yr;
SET DW.vw_Loan (KEEP=ENTDATE POCD SSNO1_RT7 OWNBR);
WHERE ENTDATE > "&_7YR" & POCD IN ("49", "50", "61", "62", "63", "64", "66", "68", "93", "97", "PB", "PO");
RUN;
DATA po_codes_5Yr;
SET po_codes_5Yr;
BADPOcode_FLAG = "X";
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
DROP ENTDATE POCD SSNO1_RT7 OWNBR;
RUN;
PROC SORT DATA=po_codes_5Yr NODUPKEY; BY SS7BRSTATE; RUN;
PROC SORT DATA=MERGEd_l_b2; BY SS7BRSTATE; RUN;
DATA MERGEd_l_b2;
MERGE MERGEd_l_b2(IN=X) po_codes_5Yr;
BY SS7BRSTATE;
IF X;
RUN;


DATA PO_codes_forever;
SET DW.vw_Loan (KEEP=ENTDATE POCD SSNO1_RT7 OWNBR);
WHERE POCD IN ("21", "94", "95", "96");
RUN;
DATA po_codes_forever;
SET po_codes_forever;
DeceASed_FLAG = "X";
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
DROP ENTDATE POCD SSNO1_RT7 OWNBR;
RUN;
PROC SORT DATA=po_codes_forever NODUPKEY; BY SS7BRSTATE; RUN;
DATA MERGEd_l_b2;
MERGE MERGEd_l_b2(IN=X) po_codes_forever;
BY SS7BRSTATE;
IF X;
RUN;

DATA con5Yr_fl;
SET DW.vw_Loan (KEEP= OWNBR SSNO1_RT7 ENTDATE CONPROFILE1);
WHERE ENTDATE > "&_7YR" & CONPROFILE1 NE "";
RUN;
DATA con5Yr_fl; *FLAG for con5;
SET con5Yr_fl;
_60=countc(CONPROFILE1,"2");
IF _60>3 THEN con5Yr_FLAG="X";
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
DROP ENTDATE SSNO1_RT7 OWNBR CONPROFILE1 _60;
RUN;
DATA con5Yr_fl_2;
SET con5Yr_fl;
IF con5Yr_FLAG="X";
RUN;
PROC SORT DATA=con5Yr_fl_2 NODUPKEY; BY SS7BRSTATE; RUN;
PROC SORT DATA=MERGEd_l_b2; BY SS7BRSTATE; RUN;
DATA MERGEd_L_B2; *MERGE PULL with con5 FLAGs;
MERGE MERGEd_L_B2(IN=X) con5Yr_fl_2;
BY SS7BRSTATE;
IF X;
RUN;


*IDENTIFY IF cusTOmer currentlY hAS an open LOAN for FB;
DATA openLOANS;
SET DW.vw_Loan (KEEP= OWNBR SSNO2 SSNO1_RT7 POCD PLCD POFFDATE PLDATE BNKRPTDATE);
WHERE POCD = "" & PLCD="" & POFFDATE="" & PLDATE="" & BNKRPTDATE="";
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
RUN;
DATA SSNO2s;
SET openLOANS;
SS7BRSTATE=CATS((SUBSTR(SSNO2,MAX(1,LENGTH(SSNO2)-6))),SUBSTR(OWNBR,1,2));
IF SSNO2 NE "" THEN OUTPUT SSNO2s;
RUN;
DATA openLOANS1;
SET openLOANS SSNO2s;
RUN;
DATA openLOANS1;
SET openLOANS1;
Open_FLAG = "X";
DROP POCD SSNO1_RT7 OWNBR PLCD POFFDATE PLDATE BNKRPTDATE SSNO2;
RUN;
PROC SORT DATA=openLOANS1 NODUPKEY; BY SS7BRSTATE; RUN;
PROC SORT DATA=MERGEd_l_b2; BY SS7BRSTATE; RUN;
DATA MERGEd_l_b2;
MERGE MERGEd_l_b2(IN=X) openLOANS1;
BY SS7BRSTATE;
IF X;
RUN;
DATA MERGEd_l_b2;
SET MERGEd_l_b2;
IF camp_tYpe="XS" THEN open_FLAG="";
RUN;



*IDENTIFY IF cusTOmer currentlY hAS an open LOAN for XS;
DATA openLOANSXs;
SET DW.vw_Loan (KEEP= SSNO2 SSNO1 POCD PLCD POFFDATE PLDATE BNKRPTDATE);
WHERE POCD = "" & PLCD="" & POFFDATE="" & PLDATE="" & BNKRPTDATE="";
RUN;
DATA SSNO2s2;
SET openLOANSXs;
IF SSNO2 NE "" THEN OUTPUT SSNO2s2;
RUN;
DATA SSNO2s2;
SET SSNO2s2;
SSNO1=SSNO2;
RUN;
DATA openLOANS1Xs;
SET openLOANSXs SSNO2s2;
RUN;
DATA openLOANS1Xs;
SET openLOANS1Xs;
Open_FLAG = "X";
DROP POCD PLCD POFFDATE PLDATE BNKRPTDATE SSNO2;
RUN;
PROC SORT DATA=openLOANS1Xs NODUPKEY; BY SSNO1; RUN;
DATA unmadesDROP MERGEd_l_b3;
SET MERGEd_l_b2;
IF made_unmade="UNMADE" THEN OUTPUT unmadesDROP;
else OUTPUT MERGEd_l_b3;
RUN;
PROC SORT DATA=unmadesDROP; BY SSNO1; RUN;
DATA unmadesDROP;
MERGE unmadesDROP(IN=X) openLOANS1Xs;
BY SSNO1;
IF X;
RUN;

DATA MERGEd_l_b2;
SET MERGEd_l_b3 unmadesDROP;
RUN;


DATA openLOANS2;
SET DW.vw_Loan (KEEP= OWNBR SSNO2 SSNO1_RT7 POCD PLCD POFFDATE PLDATE BNKRPTDATE);
WHERE POCD = "" & PLCD="" & POFFDATE="" & PLDATE="" & BNKRPTDATE="";
SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
RUN;
DATA SSNO2s;
SET openLOANS2;
SS7BRSTATE=CATS((SUBSTR(SSNO2,MAX(1,LENGTH(SSNO2)-6))),SUBSTR(OWNBR,1,2));
IF SSNO2 NE "" THEN OUTPUT SSNO2s;
RUN;
DATA openLOANS3;
SET openLOANS2 SSNO2s;
RUN;
DATA openLOANS4;
SET openLOANS3;
Open_FLAG2 = "X";
IF SS7BRSTATE = "" THEN SS7BRSTATE=CATS(SSNO1_RT7,SUBSTR(OWNBR,1,2));
DROP POCD SSNO2 SSNO1_RT7 OWNBR PLCD POFFDATE PLDATE BNKRPTDATE;
RUN;
PROC SORT DATA=openLOANS4; BY SS7BRSTATE; RUN;
DATA oNE_open mult_open;
SET openLOANS4;
BY SS7BRSTATE;
IF FIRST.SS7BRSTATE AND LAST.SS7BRSTATE THEN OUTPUT oNE_open;
else OUTPUT mult_open;
RUN;
PROC SORT DATA=mult_open NODUPKEY; BY SS7BRSTATE; RUN;
PROC SORT DATA=MERGEd_l_b2; BY SS7BRSTATE; RUN;
DATA MERGEd_l_b2;
MERGE MERGEd_l_b2(IN=X) mult_open;
BY SS7BRSTATE;
IF X;
RUN;





*FLAG INcomplete INfo;
*FLAG null DOB;
*FIND STATES OUTsIDe of footprINt;
*FLAG DNS DNH;
*FLAG nonmatchINg branch STATE AND BORROWER STATE;
*FLAG BAD SSNS;

DATA MERGEd_L_B2; 
SET MERGEd_L_B2;
ADR1=STRIP(ADR1);
ADR2=STRIP(ADR2);
CITY=STRIP(CITY);
STATE=STRIP(STATE);
ZIP=STRIP(ZIP);
CONFIDENTIAL=STRIP(CONFIDENTIAL);
SOLICIT=STRIP(SOLICIT);
FIRSTNAME=COMPRESS(FIRSTNAME,'1234567890!@#$^&*()''"%');
LASTNAME=COMPRESS(LASTNAME,'1234567890!@#$^&*()''"%');
IF ADR1="" THEN MissINgINfo_FLAG = "X"; *FLAG INcomplete INfo;
IF STATE="" THEN MissINgINfo_FLAG = "X"; *FLAG INcomplete INfo;
IF FIRSTNAME="" THEN MissINgINfo_FLAG = "X"; *FLAG INcomplete INfo;
IF LASTNAME="" THEN MissINgINfo_FLAG = "X"; *FLAG INcomplete INfo;
IF STATE NOT IN ("AL", "GA", "NC", "NM", "OK", "SC", "TN", "TX", "VA") THEN OOS_FLAG = "X"; *FIND STATES OUTsIDe of footprINt;
IF CONFIDENTIAL = "Y" THEN DNS_DNH_FLAG = "X";  *FLAG CONFIDENTIAL;
IF SOLICIT = "N" THEN DNS_DNH_FLAG = "X";  *FLAG DNS;
IF CEASEANDDESIST = "Y" THEN DNS_DNH_FLAG = "X";  *FLAG CANDD;
IF SSNO1="" THEN SSNO1=SSNO;
IF OWNBR IN ("600" , "9000" , "198" , "1", "0001" , "0198" , "0600") THEN BADBranch_FLAG="X";
IF SUBSTR(OWNBR,3,2)="99" THEN BADBranch_FLAG="X";
_60=countc(CONPROFILE1,"2");
_90=countc(CONPROFILE1,"3");
_120a=countc(CONPROFILE1,"4");
_120b=countc(CONPROFILE1,"5");
_120c=countc(CONPROFILE1,"6");
_120d=countc(CONPROFILE1,"7");
_120e=countc(CONPROFILE1,"8");
_90plus=sum(_90,_120a,_120b,_120c,_120d,_120e);
IF _60>2 | _90plus>2 THEN conprofile_FLAG="X";
_9s=countc(CONPROFILE1,"9");
IF _9s>10 THEN lessthan2_FLAG = "X";
XNO_TRUEDUEDATE2=INPUT(SUBSTR(XNO_TRUEDUEDATE,6,2)||'/'||SUBSTR(XNO_TRUEDUEDATE,9,2)||'/'||SUBSTR(XNO_TRUEDUEDATE,1,4),mmddYY10.);
FIRSTPYDATE2=INPUT(SUBSTR(FIRSTPYDATE,6,2)||'/'||SUBSTR(FIRSTPYDATE,9,2)||'/'||SUBSTR(FIRSTPYDATE,1,4),mmddYY10.);
Pmt_daYs=XNO_TRUEDUEDATE2-FIRSTPYDATE2;
IF pmt_daYs<60 THEN lessthan2_FLAG="X";
IF pmt_daYs = . & _9s <10 THEN lessthan2_FLAG="";
IF pmt_daYs>59 & _9s>10 THEN lessthan2_FLAG=""; *pmt_daYs calculation wINs over conprofile;
eQUITYt=(XNO_AVAILCREDIT/XNO_TDUEPOFF)*100;
IF eQUITYt <10 THEN et_FLAG="X";
IF XNO_AVAILCREDIT<100 THEN et_FLAG="X";
IF OWNBR = "0251" THEN OWNBR="0580";
IF OWNBR = "0252" THEN OWNBR="0683";
IF OWNBR = "0253" THEN OWNBR="0581";
IF OWNBR = "0254" THEN OWNBR="0582";
IF OWNBR = "0255" THEN OWNBR="0583";
IF OWNBR = "0256" THEN OWNBR="1103";
IF ZIP=:"36264" & OWNBR="0877" THEN OWNBR="0870";
IF OWNBR="0877" THEN OWNBR="0806";
IF OWNBR="0159" THEN OWNBR="0132";
IF ZIP=:"29659" & OWNBR="0152" THEN OWNBR="0121";
IF OWNBR="0152" THEN OWNBR="0115";
IF OWNBR="0885" THEN OWNBR="0802";
IF OWNBR="0302" THEN OWNBR="0133";
IF OWNBR="0102" THEN OWNBR="0303";
IF OWNBR="0150" THEN OWNBR="0105";
IF OWNBR="0890" THEN OWNBR="0875";
IF OWNBR = "1016" THEN OWNBR="1008";
IF OWNBR="1003" AND ZIP=:"87112" THEN OWNBR="1013";
RUN;


DATA MERGEd_l_b2;
SET MERGEd_l_b2;
IF camp_tYpe="FB" THEN DO;
IF OWNST NE STATE THEN STATE_Mismatch_FLAG = "X"; *FLAG nonmatchINg branch STATE AND BORROWER STATE;
lessthan2_FLAG="";
et_FLAG = "";
END;
IF camp_tYpe="XS" & made_unmade="UNMADE" THEN et_FLAG="";
RUN;



*PULL AND MERGE dlq INfo for fbs;
PROC FORMAT;
   value cdfmt
   1 = 'Current'
   2 = '1-29cd'
   3 = '30-59cd'
   4 = '60-89cd'
   5 = '90-119cd'
   6 = '120-149cd'
   7 = '150-179cd'
   8 = '180+cd'
   other=' ';
RUN;
DATA temp;   
   SET DW.vw_Loan(KEEP=BRACCTNO ENTDATE POFFDATE POCD CLASSTRANSLATION LNAMT CONPROFILE1 
                       brtrffg SSNO1_RT7 WHERE=(POCD IN ("10","13","50") AND POFFDATE > "&_6YR"));
   entdt = INPUT(SUBSTR(ENTDATE,6,2)||'/'||SUBSTR(ENTDATE,9,2)||'/'||SUBSTR(ENTDATE,1,4),mmddYY10.);
   podt = INPUT(SUBSTR(POFFDATE,6,2)||'/'||SUBSTR(POFFDATE,9,2)||'/'||SUBSTR(POFFDATE,1,4),mmddYY10.);
   IF POFFDATE > "&_1DAY" THEN delete; 													   
   IF PUT(entdt,YYmmn6.) = PUT(podt,YYmmn6.) THEN delete;    
   DROP POFFDATE ENTDATE POCD;
RUN;
PROC SORT NODUPKEY; BY BRACCTNO; RUN;
DATA atb;
   SET DW.atb_DATA(KEEP=BRACCTNO AGE2 Yearmonth);    
   poacctno = BRACCTNO*1;   
   atbdt = INPUT(SUBSTR(Yearmonth,6,2)||'/'||SUBSTR(Yearmonth,9,2)||'/'||SUBSTR(Yearmonth,1,4),mmddYY10.);   
   IF AGE2 =: '1' THEN AGE2 = '1.Current';   
   KEEP atbdt AGE2 BRACCTNO;
RUN;
PROC SORT NODUPKEY; BY BRACCTNO atbdt; RUN;
DATA temp;     
   MERGE temp(IN=a) atb(IN=b);
   BY BRACCTNO;
   IF a;  
   cd = SUBSTR(AGE2,1,1)*1;   
   AGE = INtck('month',atbdt,podt); 
   IF      AGE = 1 THEN delq1 = cd;
   else IF AGE = 2 THEN delq2 = cd;
   else IF AGE = 3 THEN delq3 = cd;
   else IF AGE = 4 THEN delq4 = cd;
   else IF AGE = 5 THEN delq5 = cd;
   else IF AGE = 6 THEN delq6 = cd;
   else IF AGE = 7 THEN delq7 = cd;
   else IF AGE = 8 THEN delq8 = cd;
   else IF AGE = 9 THEN delq9 = cd;
   else IF AGE =10 THEN delq10= cd;
   else IF AGE =11 THEN delq11= cd;
   else IF AGE =12 THEN delq12= cd;
   else delete;
       IF cd>4 THEN cd90 = 1; *IF cd is greater than 60-89 daYs late, SET cd90 TO 1;
    IF cd>3 THEN cd60 = 1; *IF cd is greater than 30-59 daYs late, SET cd60 TO 1;
   IF cd>2 THEN cd30 = 1; *IF cd is greater than 1-29 daYs late, SET cd30 TO 1;
   IF AGE<7 THEN DO;
		IF cd=3 THEN recent6=1; *NOTe 30-59s IN LAST siX months of LAST open LOAN;
		END;
		else IF 6<AGE<13 THEN DO;
		IF cd=3 THEN FIRST6=1; *NOTe 30-59s FROM 7 TO 12 months of LAST open LOAN;
		END;
   FORMAT podt entdt atbdt mmddYY10.;
RUN;
DATA temp2;
SET temp;
LAST12=sum(recent6,FIRST6); *count the numBEr of 30-59s IN the LAST Year WHEN fb had open LOAN;
RUN;
PROC summarY DATA=temp2 nwaY missINg;
   clASs CLASSTRANSLATION SSNO1_RT7 BRACCTNO entdt podt LNAMT CONPROFILE1;
   var delq1-delq12 recent6 LAST12 FIRST6 cd90 cd60 cd30;
   OUTPUT OUT=fINal(DROP=_tYpe_ _freq_) sum=;
RUN; 
DATA fbdlq;
   SET fINal;
   IF cd60 > 0 THEN ever60 = 'Y'; else ever60 = 'N';
   times30 = cd30;
   IF times30 = . THEN times30 = 0;
   DROP cd30;
   FORMAT delq1-delq12 cdfmt.;
RUN;
PROC SORT DATA=fbdlq; BY BRACCTNO; RUN;
 DATA fb;
 SET MERGEd_l_b2;
 IF camp_tYpe="FB";
 RUN;
PROC SORT DATA=fb; *SORT TO MERGE; BY BRACCTNO; RUN;
DATA fbwithdlq; *MERGE PULL AND dql INFORMATion;
MERGE fb(IN=X) fbdlq(IN=Y);
BY BRACCTNO;
IF X=1;
RUN;


*****************************************;
*PULL AND MERGE dlq INfo for Xs;
DATA atb; 
   SET DW.atb_DATA(KEEP=BRACCTNO AGE2 Yearmonth WHERE=(Yearmonth BEtween "&_1YR" AND "&_1DAY"));  
   atbdt = INPUT(SUBSTR(Yearmonth,6,2)||'/'||SUBSTR(Yearmonth,9,2)||'/'||SUBSTR(Yearmonth,1,4),mmddYY10.);     
   AGE = INtck('month',atbdt,"&sYsDATE"d);
cd = SUBSTR(AGE2,1,1)*1;   
 *i.e. for AGE=1: THIS is most recent month. Fill delq1, which is delq for month 1, with delq status (cd);
   IF      AGE = 1 THEN delq1 = cd;
   else IF AGE = 2 THEN delq2 = cd;
   else IF AGE = 3 THEN delq3 = cd;
   else IF AGE = 4 THEN delq4 = cd;
   else IF AGE = 5 THEN delq5 = cd;
   else IF AGE = 6 THEN delq6 = cd;
   else IF AGE = 7 THEN delq7 = cd;
   else IF AGE = 8 THEN delq8 = cd;
   else IF AGE = 9 THEN delq9 = cd;
   else IF AGE =10 THEN delq10= cd;
   else IF AGE =11 THEN delq11= cd;
   else IF AGE =12 THEN delq12= cd;
   IF cd>4 THEN cd90 = 1; *IF cd is greater than 60-89 daYs late, SET cd90 TO 1;
   IF cd>3 THEN cd60 = 1; *IF cd is greater than 30-59 daYs late, SET cd60 TO 1;
   IF cd>2 THEN cd30 = 1; *IF cd is greater than 1-29 daYs late, SET cd30 TO 1;
   IF AGE<7 THEN DO;
		IF cd=3 THEN recent6=1; *NOTe 30-59s IN LAST siX months;
		END;
		else IF 6<AGE<13 THEN DO;
		IF cd=3 THEN FIRST6=1; *NOTe 30-59s FROM 7 TO 12 months ago;
		END;
   KEEP BRACCTNO delq1-delq12 cd cd30 cd60 cd90 AGE2 atbdt AGE FIRST6 recent6;
RUN;
DATA atb2;
SET atb;
LAST12=sum(recent6,FIRST6); *count the numBEr of 30-59s IN the LAST Year;
RUN;
*count cd30, cd60,recent6,FIRST6 BY BRACCTNO (*reCALL LOAN potentiALLY counted for each month);
PROC summarY DATA=atb2 nwaY missINg;
   clASs BRACCTNO;
   var delq1-delq12 recent6 LAST12 FIRST6 cd90 cd60 cd30;
   OUTPUT OUT=atb3(DROP=_tYpe_ _freq_) sum=;
RUN; 
DATA atb4; *CREATE NEW counter variables;
   SET atb3;
   IF cd60 > 0 THEN ever60 = 'Y'; else ever60 = 'N';
   times30 = cd30;
   IF times30 = . THEN times30 = 0;
   IF recent6 = null THEN recent6=0;
   IF FIRST6 = null THEN FIRST6=0;
   IF LAST12 = null THEN LAST12=0;
   DROP cd30;
   FORMAT delq1-delq12 cdfmt.;
RUN;
PROC SORT DATA=atb4 NODUPKEY; BY BRACCTNO; RUN; *SORT TO MERGE;
DATA Xsdlq; SET atb4; DROP null; *DROPpINg the null column (NOT nulls IN DATASET); RUN;



DATA Xs;
SET MERGEd_l_b2;
IF camp_tYpe="XS";
RUN;
PROC SORT DATA=Xs; *SORT TO MERGE; BY BRACCTNO; RUN;
DATA Xswithdlq; *MERGE PULL AND dql INFORMATion;
MERGE Xs(IN=X) Xsdlq(IN=Y);
BY BRACCTNO;
IF X=1;
RUN;

DATA MERGEd_l_b2;
SET fbwithdlq Xswithdlq;
RUN;


*APPlY ALL delINquencY related FLAGs;
DATA MERGEd_l_b2; *FLAG for BAD dlqatb;
SET MERGEd_l_b2;
IF cd60>1 or cd90>1 THEN DLQ_FLAG="X";
RUN;

PROC SORT DATA=MERGEd_l_b2 OUT= deduped NODUPKEY; BY BRACCTNO; RUN;


*EXport FLAGGEd File;
/*
PROC eXport DATA=deduped OUTfile="&FINALEXPORTFLAGGED" DBMS=tab;
RUN;
*/

 *CREATE fINal file for DROPs;
 DATA fINal;
 SET deduped;
 IF ENTDATE="" THEN ENTDATE=1;
 RUN;


  DATA WaterfALL;
 LENGTH Criteria $50 Count 8.;
 INfile DATAlINEs DLM="," tRUNcover;
 INPUT Criteria $ Count;
 DATAlINEs;
TCI DATA,
XS TOtal,
FB TOtal,
XS + FB TOtal,	
Delete cust IN BAD Branches,	
Delete cust with MissINg INfo,	
Delete cust OUTsIDe of FootprINt,	
Delete WHERE STATE/OWNST Mismatch,
Delete FB With Open LOAN,
Delete AnY CusTOmer with >1 LOAN,
Delete cust with BAD POCODE,
Delete DeceASed,
Delete IF Less than Two PaYments Made,	
Delete for ATB DelINquencY,	
Delete for Conprofile DelINquencY,
Delete for 5 Yr. Conprofile DelINquencY,
Delete for BankruptcY (5Yr),
Delete for StatFLAG (5Yr),
Delete for TRW Status (5Yr),
Delete IF DNS or DNH,
Delete NC AUTO Unmades,	
Delete XS BAD FICOs,
Delete IF EQUITY ThreshhOLD NOT met,		
;
RUN;
	



PROC SQL; *Count obs; CREATE TABLE count AS SELECT count(*) AS Count FROM tci; QUIT;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM Xs_TOtal; QUIT;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fb; QUIT;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM MERGEd_L_B_Xs_fb2; QUIT;
DATA fINal; SET fINal; IF BADBranch_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;
DATA fINal; SET fINal; IF MissINgINfo_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF OOS_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF STATE_Mismatch_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF open_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;
DATA fINal; SET fINal; IF open_FLAG2=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;
DATA fINal; SET fINal; IF BADPOcode_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF deceASed_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;
DATA fINal; SET fINal; IF lessthan2_FLAG=""; RUN; 
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF dlq_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;
DATA fINal; SET fINal; IF conprofile_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;
DATA fINal; SET fINal; IF con5Yr_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;  
DATA fINal; SET fINal; IF bk5_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF statfl_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF TRW_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF DNS_DNH_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF NCAUTOUn_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT; 
DATA fINal; SET fINal; IF BADfico_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;
DATA fINal; SET fINal; IF et_FLAG=""; RUN;
PROC SQL; INsert INTO count SELECT count(*) AS Count FROM fINal; QUIT;

PROC prINt DATA=count noobs;  *PrINt FINal Count TABLE;
RUN;
PROC prINt DATA=waterfALL;  *PrINt FINal Count TABLE;
RUN;


*EXport FINal File;
DATA fbXsmita;
SET fINal;
RUN;
/*
PROC eXport DATA=fINal OUTfile="&FINALEXPORTDROPPED" DBMS=tab;
RUN;
*/

*SEND TO DOD;
DATA mla;
SET fINal;
KEEP SSNO1 DOB LASTNAME FIRSTNAME MIDDLENAME BRACCTNO;
RUN;
PROC DATASETs;
MODIFY mla;
RENAME DOB ="DATE of Birth"n SSNO1="Social SecuritY NumBEr (SSN)"n LASTNAME="LAST NAME"n FIRSTNAME="FIRST NAME"n MIDDLENAME="MIDDLE NAME"n BRACCTNO="CusTOmer Record ID"n;
RUN;
DATA fINalmla;
LENGTH "Social SecuritY NumBEr (SSN)"n $ 9 "DATE of Birth"n $ 8 "LAST NAME"n $ 26 "FIRST NAME"n $20 "MIDDLE NAME"n $ 20  "CusTOmer Record ID"n $ 28;
SET mla;
RUN;
PROC prINt DATA=fINalmla (obs=10);
RUN;
PROC contents DATA=fINalmla;
RUN;

DATA split1 split2;
SET fINalmla;
IF "Social SecuritY NumBEr (SSN)"n=:"1" | "Social SecuritY NumBEr (SSN)"n=:"2" THEN OUTPUT split1;
else OUTPUT split2;
RUN;
DATA _NULL_;
 SET split1;
 file "&EXPORTMLA1"; 
 PUT @1 "Social SecuritY NumBEr (SSN)"n @10 "DATE of Birth"n @ 18 "LAST NAME"n @ 44 "FIRST NAME"n @ 64 "MIDDLE NAME"n @ 84 "CusTOmer Record ID"n ;
 RUN; 
 DATA _NULL_;
 SET split2;
 file "&EXPORTMLA2";  
 PUT @1 "Social SecuritY NumBEr (SSN)"n @10 "DATE of Birth"n @ 18 "LAST NAME"n @ 44 "FIRST NAME"n @ 64 "MIDDLE NAME"n @ 84 "CusTOmer Record ID"n ;
 RUN; 



*STEP 2: IMPORT file FROM DOD, APPEND offer INFORMATion, AND APPEND PB IF APPlicable;
fileNAME mla1 "\\mktg-APP01\E\Production\MLA\MLA-OUTPUT files FROM WEBSITE\FBITAp1.tXt";
DATA mla1;
INfile mla1;
INPUT SSNO1 $ 1-9 DOB $ 10-17 LASTNAME $ 18-43 FIRSTNAME $ 44-63 MIDDLENAME $ 64-83  BRACCTNO $ 84-120 mla_DOd $121-145;
mla_status=SUBSTR(mla_DOd,1,1);
RUN;
fileNAME mla2 "\\mktg-APP01\E\Production\MLA\MLA-OUTPUT files FROM WEBSITE\FBITAp2.tXt";
DATA mla2;
INfile mla2;
INPUT SSNO1 $ 1-9 DOB $ 10-17 LASTNAME $ 18-43 FIRSTNAME $ 44-63 MIDDLENAME $ 64-83  BRACCTNO $ 84-120 mla_DOd $121-145;
mla_status=SUBSTR(mla_DOd,1,1);
RUN;

DATA mla1;
SET mla1 mla2;
RUN;
PROC contents DATA=mla1;
RUN;



PROC SORT DATA=fbXsmita;
BY BRACCTNO;
RUN;
PROC SORT DATA=mla1;
BY BRACCTNO;
RUN;
DATA fINalhh;
MERGE fbXsmita(IN=X) mla1;
BY BRACCTNO;
IF X;
RUN;

*Count for WaterfALL;
PROC freq DATA=fINalhh;
TABLE mla_status;
RUN;

DATA ficos;
SET fINalhh;
RENAME CRSCORE=fico;
RUN;

DATA fINalhh2;
LENGTH fico_RANGE_25pt $10 campaign_ID $25 Made_Unmade $15 CIFNO $20 custID $20 mgc $20 STATE1 $5 test_code $20;
SET ficos;
IF mla_status NOT IN ("Y","");
IF fico=0 THEN fico_RANGE_25pt= "0";
IF 0<fico<500 THEN fico_RANGE_25pt="<500";
IF 500<=fico<=524 THEN fico_RANGE_25pt= "500-524";
IF 525<=fico<=549 THEN fico_RANGE_25pt= "525-549";
IF 550<=fico<=574 THEN fico_RANGE_25pt= "550-574";
IF 575<=fico<=599 THEN fico_RANGE_25pt= "575-599";
IF 600<=fico<=624 THEN fico_RANGE_25pt= "600-624";
IF 625<=fico<=649 THEN fico_RANGE_25pt= "625-649";
IF 650<=fico<=674 THEN fico_RANGE_25pt= "650-674";
IF 675<=fico<=699 THEN fico_RANGE_25pt= "675-699";
IF 700<=fico<=724 THEN fico_RANGE_25pt= "700-724";
IF 725<=fico<=749 THEN fico_RANGE_25pt= "725-749";
IF 750<=fico<=774 THEN fico_RANGE_25pt= "750-774";
IF 775<=fico<=799 THEN fico_RANGE_25pt= "775-799";
IF 800<=fico<=824 THEN fico_RANGE_25pt= "800-824";
IF 825<=fico<=849 THEN fico_RANGE_25pt= "825-849";
IF 850<=fico<=874 THEN fico_RANGE_25pt= "850-874";
IF 875<=fico<=899 THEN fico_RANGE_25pt= "875-899";
IF 975<=fico<=999 THEN fico_RANGE_25pt= "975-999";
IF fico="" THEN fico_RANGE_25pt= "";
IF SOURCE_2 = "Retail" THEN CAMPAIGN_ID = "&Retail_ID";
IF SOURCE_2 = "Auto" THEN CAMPAIGN_ID = "&AUTO_ID";
IF camp_tYpe="FB" THEN CAMPAIGN_ID = "&FB_ID";
custID=STRIP(_n_);
Made_Unmade=madeunmade_FLAG;
offer_segment="ITA";
IF STATE1="" THEN STATE1=STATE;
IF STATE1="TX" THEN STATE1="";
IF ENTDATE=1 THEN ENTDATE="";
RUN;
DATA fINalhh2;
SET fINalhh2;
RENAME OWNBR=branch FIRSTNAME=cFNAME1 MIDDLENAME=cmNAME1 LASTNAME=cLNAME1 ADR1=caddr1 ADR2=caddr2
CITY=cCITY STATE=cst ZIP=cZIP SSNO1_RT7=SSN cd60=n_60_dpd CONPROFILE1=ConProfile;
RUN;


DATA fbXsita_hh;
LENGTH FROM_Offer_Amount 8. Up_TO_Offer 8.;
SET fINalhh2;
IF cst="NC" THEN FROM_Offer_Amount = 700;
IF cst="AL" THEN up_TO_offer=6000;
IF FROM_offer_amount = . THEN FROM_offer_amount = 600;
IF up_TO_offer = . THEN up_TO_offer = 7000;
IF branch="1019" THEN FROM_offer_amount=2501;
RUN;



*APPEND pbita;
DATA fINalhh3;
LENGTH amt_given1 8. month_split $15 numpYmnts $15 orig_amtID $15 percent $15 FROM_Offer_Amount 8. Up_TO_Offer 8.;
SET fbXsita_hh pbita_hh;
IF mla_status NE "";
RUN;
PROC SQL;
CREATE TABLE fINalesthh AS
SELECT custID, branch, cFNAME1,	cmNAME1, cLNAME1, caddr1, caddr2, cCITY, cst, cZIP,	SSN, amt_given1, FROM_offer_amount, up_TO_offer, percent,numpYmnts, camp_tYpe, orig_amtID, fico, DOB, mla_status, risk_segment, n_60_dpd, conprofile, BRACCTNO, CIFNO, campaign_ID, mgc, month_split, made_unmade, fico_RANGE_25pt, STATE1, test_code, POFFDATE, PHONE, CELLPHONE
FROM fINalhh3;
QUIT;

PROC eXport DATA=fINalesthh OUTfile="&FINALEXPORTHH" DBMS=tab;
 RUN;

 PROC eXport DATA=fINalesthh OUTfile="&FINALEXPORTED"  DBMS=csv;
 RUN;
PROC freq DATA=fINalesthh;
TABLEs mla_status Risk_Segment STATE1 cst;
RUN;



 *For WHEN pbita isn't INcluded;
DATA fINalhh3;
LENGTH amt_given1 8. month_split $15 numpYmnts $15 orig_amtID $15 percent $15 FROM_Offer_Amount 8. Up_TO_Offer 8.;
SET fbXsita_hh;
IF mla_status NE "";
RUN;
PROC SQL;
CREATE TABLE fINalesthh AS
SELECT custID, branch, cFNAME1,	cmNAME1, cLNAME1, caddr1, caddr2, cCITY, cst, cZIP,	SSN, amt_given1, FROM_offer_amount, up_TO_offer, percent,numpYmnts, camp_tYpe, orig_amtID, fico, DOB, mla_status, risk_segment, n_60_dpd, conprofile, BRACCTNO, CIFNO, campaign_ID, mgc, month_split, made_unmade, fico_RANGE_25pt, STATE1, test_code, POFFDATE, PHONE, CELLPHONE
FROM fINalhh3;
QUIT;

PROC eXport DATA=fINalesthh OUTfile="&FINALEXPORTHH2" DBMS=tab;
 RUN;

 PROC eXport DATA=fINalesthh OUTfile="&FINALEXPORTED2"  DBMS=csv;
 RUN;


PROC freq DATA=fINalesthh;
TABLEs mla_status Risk_Segment STATE1 cst;
RUN;